version: 1.54
run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gosec
    - gocyclo
    - errcheck
  disable:
    - depguard

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    # Suppress rules that conflict with our controlled plugin surface (shell exec, dynamic paths).
    excludes:
      - G104 # errors not checked (handled by errcheck)
      - G204 # subprocess can be influenced by user input (shell action is intentionally whitelisted separately)
      - G304 # file path from variable (we validate with safePath)
      - G404 # weak random number generator (not security sensitive here)
  revive:
    severity: warning
    rules:
      - name: exported
      - name: var-naming
      - name: receiver-naming
      - name: time-naming
      - name: unnecessary-stmt
      - name: unreachable-code
